[Service]
  Host = "localhost"
  Port = 1210
  Labels = []
  OpenMsg = "Edgex-Export-Receiver started"
  StaticResourcesPath = ""

[Database]
  Host = "localhost"
  Name = "edgex-export-receiver"
  Port = 27017
  Username = "su"
  Password = "su"
  Timeout = 0
  Type = ""
  [Database.Scheme]
    Event = "event"
    Application = "application"
    Node = "node"
    TaskEvent = "taskevent"
    Device = "device"
    ScheduleResult = "scheduleresult"
    EventToExecute = "eventtoexecute"
    EventExecuted = "eventexecuted"

[Edgex]
  Gateway = "10.112.170.132"

[Schedule]
  [Schedule.GetSchedule]
    Host = "10.112.221.88"
    Port = 8888
    Path = "api/v1/scheduleresult"
  [Schedule.AppSchedule]
    Host = "10.112.221.88"
    Port = 8082
    Path = "edgex/task"
