[Service]
Host = "localhost"
Port = 1210
Labels = []
OpenMsg = "Edgex-Export-Receiver started"

#Using an default memory db automatically if not configed here.
[Database]
Host = "localhost"
Name = "edgex-export-receiver"
Port = 27017
Username = "su"
Password = "su"
  [Database.Scheme]
  Event = "event"
  Application = "application"
  Node = "node"
  TaskEvent = "taskevent"
  Device = "device"
  ScheduleResult = "scheduleresult"
  EventToExecute = "eventtoexecute"
  EventExecuted = "eventexecuted"

#接收调度结果
[Schedule]
Host = "10.103.240.39"
Port = 8888
getSchedule = "getSchedule"